
spring:
  application:
    name: catalogservice
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/CatalogFinalDB
      repositories:
        enabled: true

  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  serie:
    name: SerieQueue
  movie:
    name: MovieQueue

server:
  port: 8071

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
