
spring:
  application:
    name: catalogservice
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/CatalogFinalDB
      repositories:
        enabled: true


server:
  port: 8071

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
