server:
  port: 8098
spring:
  data:
      mongodb:
        uri: mongodb://host:27017/db
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetchRegistry: false
      registerWithEureka: true
