spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: false
          lower-case-service-id: true
      routes:
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
        - id: serieservice
          uri: lb://serieservice
          predicates:
            - Path=/series/**
        - id: movieservice
          uri: lb://movieservice
          predicates:
            - Path=/movies/**

server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
