spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: false
          lower-case-service-id: true
      routes:
        - id: catalogservice
          uri: lb://catalogservice
          predicates:
            - Path=/catalog/**
        - id: serieservice
          uri: lb://serieservice
          predicates:
            - Path=/series/**
        - id: movieservice
          uri: lb://movieservice
          predicates:
            - Path=/movies/**

#security que puede romper todo y lloro
  security:
     oauth2:
       client:
         provider:
           google:
            issuer-uri: https://accounts.google.com
         registration:
           google:
             client-id: 725280996574-8o0e5n5ah1phca3t5l04gcebbnq342o0.apps.googleusercontent.com
             client-secret: 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
             scope: openid
             redirect_uri: http://localhost:8080/login/oauth2/code/google

server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
