server:
  port: 8099
spring:
  application:
    name: movieservice
    
  datasource:
    url : jdbc:mysql://localhost:3306/movieservice?createDatabaseIfNotExist=true
    username : root
    password : Nutriarosa7
    driverClassName : com.mysql.cj.jdbc.Driver
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
        
  rabbitmq: #new
    username: guest #new
    password: guest #new
    host: localhost #new
    port: 5672 #new  
queue: #new
  movie: #new
    name: MoviesQueue #new
    
message: registro up #new

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
