server:
  port: 8099
spring:
  data:
    mongodb:
      database: moviesFinal
      port: 27017
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetchRegistry: true
      registerWithEureka: true
