# server:
#   port: 8099
# spring:
#   application:
#     name: movieservice
#   jpa:
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL5Dialect
#     show-sql: true
#   datasource:
#     url: jdbc:mysql://localhost:3306/movieservice
#     username: root
#     password: Holamundo

server:
  port: 8099
spring:
  application:
    name: movieservice
  datasource:
    url : jdbc:mysql://localhost:3306/movieservice
    username : root
    password : Holamundo
    driverClassName : com.mysql.cj.jdbc.Driver
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto : update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  



# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka
#       fetchRegistry: true
#       registerWithEureka: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
